variable "datacenter" {}
variable "cluster" {}
variable "datastore" {}
variable "network" {}
variable "content_library_name" {}
variable "content_library_item_name" {}
variable "content_library_item_type" {}

variable "host_name" {}
variable "domain" {}
variable "guest_id" {}
variable "num_cpus" {}
variable "memory" {}
variable "disk_size" {}
variable "eagerly_scrub" {}
variable "thin_provisioned" {}
variable "ipv4_address" {}
variable "ipv4_netmask" {}
variable "ipv4_gateway" {}
